### PR TITLE
Add "topmost" support on OS X/Linux

### PR DESCRIPTION
**Pull request by lethosor**
The overrideredirect Tk flag only works when the window is initially created on OS X - setting it later with overrideredirect() disables window controls but doesn't hide them, and changing it back doesn't re-enable the controls. This probably varies among window managers on Linux, so I chose to disable overrideredirect() there as well - the topmost flag is probably more useful for most users, in any case.

### CODE REVIEW

**Comment by lethosor** [comment]
Question: do you prefer to have pull requests based on master or develop? It looks like you work most often in develop, but it's currently behind master.

**Comment by NuAoA** [comment]
Develop is fine, There is a few changes I made to the readme that I haven't merged over yet. I should probably take care of that. 

I'm surprised you have issues with overrideredirect, I thought there would be issues with topmost, since [according to these docs](http://effbot.org/tkinterbook/wm.htm#wm.Wm.wm_attributes-method), its windows only:

topmost=
(Windows) If set, this window is always placed on top of other windows. Note that in this release, this  attribute must be given as “-topmost”.

**Comment by lethosor** [comment]
`wm_attributes()` passes its arguments directly to Tk/Tcl, and the `-topmost` flag looks like it's supported on all three platforms relevant here as of Tk 8.5: http://wiki.tcl.tk/9457. I suspect the effbot.org docs are a bit outdated - they make a few references to "this release", which is probably whatever release was current in November 2005 (mentioned [here](http://effbot.org/tkinterbook/)). I'm not entirely sure what will happen if that flag isn't supported, though, so catching Tk exceptions might be a good idea.

**Comment by NuAoA** [comment]
Ah, I knew those docs were kind of outdated but never knew they were that outdated. 

I tested overrideredirect() on debian, it appears to do nothing at all, so I guess we can just leave it as is. The '-topmost' flag is what I was going for.

**Pull request merged**
