### PR TITLE
Fix some issues on OS X

### PR DESCRIPTION
**Pull request by lethosor**
- Use ttk instead of Tix (if this causes widgets to fall back to the old Tk style on Windows, there are a variety of ways to work around that - the ttk widgets should look more modern)
- Make menu bar display correctly - this involves adding all menu options to a submenu, since OS X can't handle menu options that aren't in a submenu

Note that I haven't tested this on Linux yet - it's possible that the latter fix will need to be applied there as well (depending on the desktop environment)

### CODE REVIEW

**Comment by NuAoA** [comment]
Hey, thanks for the input i'm taking a look at it now.

The only reason I am using Tix is because a) This is my first time diving into tkinter so I don't know whats what, and b) the only module that i've found online that provides a dialog to choose fonts (tkFontChooser.py) used Tix, which caused a crash when my main_gui() class inherited Tkinter.tk, so I made the switch.

With your change this issue comes back (try changing the font, it will crash), but i'll take a look at the tkFontChooser to see if I can make it work.

**Comment by lethosor** [comment]
Oh, tkFontChooser is Tix-based.

**Comment by lethosor** [comment]
I can't find the menu with the "Change Font" choice at all. Where is it supposed to show up?

**Comment by NuAoA** [comment]
Yea, tkFontChooser is a nasty piece of code. I think I had to modify it to actually get it running properly.  

If you want to change the font, right click on the window and there is a pulldown with some extra options.

**Comment by lethosor** [comment]
Turns out the issue was that Tkinter uses `Button-2` for the right mouse button on OS X and `Button-3` for the middle button (which is the opposite of what it uses on Windows). Tkinter is fun (but is admittedly one of the most reliably available/distributable/portable toolkits available, so I suppose I can't complain too much).

I removed the `default` keyword argument from a couple calls to [`iconbitmap`](http://effbot.org/tkinterbook/wm.htm#Tkinter.Wm.iconbitmap-method), which doesn't look like it should cause a problem elsewhere, but let me know if it does.

I can't get the font chooser to work (without Tix), but it looks simple enough to rewrite with just Tk/ttk.

**Comment by NuAoA** [comment]
Ok, I removed Tix from tkFontChooser, everything else seems to be functional. A few more tweaks and i'll merge

**Pull request merged**
